a= "Python is very important language for Artificial Intelligence: "
print(len(a))
print(a.count)
print(a.lower())
print(a.upper())
print(a.index)
print(a.capitalize())
print(a.title())
print(a.find("v"))
print(a.format())
print(a.center(8,"*"))